Import("env")

env.Program(target="show", source="show.c")
env.Program(target="smooth", source="smooth.c")
env.Program(target="downscale", source="downscale.c")
env.Program(target="canny", source="canny.c")
